// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import ChatBotWrapper from "@/components/ChatBot/ChatBotWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "TourMitra",
//   description: "Generated by create next app",
  
// };


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
      
//       <body>
//         <Navbar/>
//         <main>
//         {children}
//         </main>
//         <Footer/>
//         <ChatBotWrapper />
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css"; // Sab styling yahan se aati hai, isliye theme same rahegi
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ChatBotWrapper from "@/components/ChatBot/ChatBotWrapper";

export const metadata: Metadata = {
  title: "TourMitra",
  description: "Elite Travel Experience",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      {/* Font-sans use karne se system ka best font load hoga bina error ke */}
      <body className="font-sans">
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
        <ChatBotWrapper />
      </body>
    </html>
  );
}