// ── tripsData.ts
// Place this file at: /data/tripsData.ts

export type TripCategory =
  | "domestic"
  | "international"
  | "adventure"
  | "honeymoon";

export type TravelGroup =
  | "family"
  | "friends"
  | "solo"
  | "couple";

export interface Trip {
  id: number;
  title: string;
  destination: string;
  country: string;
  image: string;            // Unsplash URL
  price: number;            // INR
  days: number;
  nights: number;
  category: TripCategory;
  groupTypes: TravelGroup[]; // which group types this trip suits
  rating: number;           // 1-5
  reviews: number;
  highlights: string[];
  includes: string[];       // e.g. "Flight", "Hotel", "Meals"
  badge?: string;           // e.g. "Bestseller", "New"
}

export const TRIPS: Trip[] = [
  // ── DOMESTIC ────────────────────────────────────────────────────────────
  {
    id: 1,
    title: "Golden Triangle Express",
    destination: "Delhi • Agra • Jaipur",
    country: "India",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    price: 18500,
    days: 6,
    nights: 5,
    category: "domestic",
    groupTypes: ["family", "couple", "friends"],
    rating: 4.7,
    reviews: 342,
    highlights: ["Taj Mahal sunrise visit", "Amber Fort jeep ride", "Hawa Mahal walk"],
    includes: ["Hotel", "Breakfast", "Sightseeing", "AC Transport"],
    badge: "Bestseller",
  },
  {
    id: 2,
    title: "Goa Beach Bliss",
    destination: "North & South Goa",
    country: "India",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    price: 12999,
    days: 4,
    nights: 3,
    category: "domestic",
    groupTypes: ["friends", "couple", "solo"],
    rating: 4.5,
    reviews: 518,
    highlights: ["Baga Beach parties", "Old Goa churches", "Spice plantation tour"],
    includes: ["Hotel", "Breakfast", "Airport Transfer"],
    badge: "Hot Deal",
  },
  {
    id: 3,
    title: "Manali Winter Escape",
    destination: "Manali, Himachal Pradesh",
    country: "India",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
    price: 15800,
    days: 5,
    nights: 4,
    category: "domestic",
    groupTypes: ["friends", "couple", "family"],
    rating: 4.8,
    reviews: 276,
    highlights: ["Rohtang Pass snow", "Solang Valley skiing", "Old Manali cafe trail"],
    includes: ["Hotel", "All Meals", "Snowmobile Activity", "Transport"],
  },
  {
    id: 4,
    title: "Kerala Backwaters & Beaches",
    destination: "Kochi • Munnar • Alleppey",
    country: "India",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    price: 22000,
    days: 7,
    nights: 6,
    category: "domestic",
    groupTypes: ["family", "couple"],
    rating: 4.9,
    reviews: 431,
    highlights: ["Houseboat overnight stay", "Tea garden walk", "Kathakali performance"],
    includes: ["Hotel + Houseboat", "Breakfast", "Sightseeing", "Flight"],
    badge: "Trending",
  },
  {
    id: 5,
    title: "Rajasthan Royal Trail",
    destination: "Jaipur • Jodhpur • Udaipur",
    country: "India",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed31672?w=800&auto=format&fit=crop&q=80",
    price: 28000,
    days: 8,
    nights: 7,
    category: "domestic",
    groupTypes: ["family", "couple", "friends"],
    rating: 4.7,
    reviews: 389,
    highlights: ["Lake Pichola boat ride", "Mehrangarh Fort", "Desert camp dinner"],
    includes: ["Heritage Hotel", "Breakfast & Dinner", "AC Transport", "Guide"],
    badge: "Bestseller",
  },
  {
    id: 6,
    title: "Andaman Island Hopper",
    destination: "Port Blair • Havelock • Neil",
    country: "India",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    price: 35000,
    days: 6,
    nights: 5,
    category: "domestic",
    groupTypes: ["couple", "friends", "family"],
    rating: 4.8,
    reviews: 213,
    highlights: ["Radhanagar Beach", "Scuba diving", "Cellular Jail light show"],
    includes: ["Hotel", "Breakfast", "Ferry Tickets", "Flight"],
  },

  // ── INTERNATIONAL ────────────────────────────────────────────────────────
  {
    id: 7,
    title: "Bangkok & Pattaya Explorer",
    destination: "Bangkok • Pattaya",
    country: "Thailand",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&auto=format&fit=crop&q=80",
    price: 42000,
    days: 6,
    nights: 5,
    category: "international",
    groupTypes: ["friends", "couple", "family"],
    rating: 4.6,
    reviews: 622,
    highlights: ["Grand Palace tour", "Floating market", "Pattaya beach club"],
    includes: ["Hotel", "Breakfast", "Return Flight", "Visa Assistance"],
    badge: "Bestseller",
  },
  {
    id: 8,
    title: "Dubai Luxury Getaway",
    destination: "Dubai, UAE",
    country: "UAE",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop&q=80",
    price: 75000,
    days: 5,
    nights: 4,
    category: "international",
    groupTypes: ["couple", "family", "friends"],
    rating: 4.8,
    reviews: 487,
    highlights: ["Burj Khalifa top floor", "Desert safari", "Dubai Mall & Fountain"],
    includes: ["5-Star Hotel", "Breakfast", "Return Flight", "Desert Safari"],
    badge: "Premium",
  },
  {
    id: 9,
    title: "Singapore & Sentosa",
    destination: "Singapore",
    country: "Singapore",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&auto=format&fit=crop&q=80",
    price: 68000,
    days: 6,
    nights: 5,
    category: "international",
    groupTypes: ["family", "couple", "friends"],
    rating: 4.7,
    reviews: 341,
    highlights: ["Universal Studios", "Marina Bay Sands", "Gardens by the Bay"],
    includes: ["Hotel", "Breakfast", "Return Flight", "Universal Studios Ticket"],
  },
  {
    id: 10,
    title: "Paris Romance",
    destination: "Paris, France",
    country: "France",
    image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&auto=format&fit=crop&q=80",
    price: 145000,
    days: 7,
    nights: 6,
    category: "international",
    groupTypes: ["couple"],
    rating: 4.9,
    reviews: 198,
    highlights: ["Eiffel Tower dinner", "Louvre Museum", "Seine River cruise"],
    includes: ["Boutique Hotel", "Breakfast", "Return Flight", "City Tour"],
    badge: "Luxury",
  },
  {
    id: 11,
    title: "Bali Spiritual Retreat",
    destination: "Ubud • Seminyak • Nusa Dua",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80",
    price: 55000,
    days: 7,
    nights: 6,
    category: "international",
    groupTypes: ["couple", "solo", "friends"],
    rating: 4.8,
    reviews: 529,
    highlights: ["Tegallalang rice terrace", "Uluwatu sunset", "Balinese cooking class"],
    includes: ["Villa", "Breakfast", "Return Flight", "Spa Session"],
    badge: "Trending",
  },
  {
    id: 12,
    title: "Maldives Overwater Escape",
    destination: "Maldives",
    country: "Maldives",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&auto=format&fit=crop&q=80",
    price: 185000,
    days: 5,
    nights: 4,
    category: "international",
    groupTypes: ["couple"],
    rating: 5.0,
    reviews: 143,
    highlights: ["Overwater bungalow", "Snorkelling with manta rays", "Private beach dinner"],
    includes: ["Overwater Villa", "All Meals", "Return Flight", "Speedboat Transfer"],
    badge: "Luxury",
  },

  // ── ADVENTURE ────────────────────────────────────────────────────────────
  {
    id: 13,
    title: "Spiti Valley Expedition",
    destination: "Spiti, Himachal Pradesh",
    country: "India",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
    price: 24000,
    days: 9,
    nights: 8,
    category: "adventure",
    groupTypes: ["friends", "solo"],
    rating: 4.9,
    reviews: 167,
    highlights: ["Key Monastery", "Chandratal Lake camp", "Kunzum Pass crossing"],
    includes: ["Camping + Guesthouses", "All Meals", "Bike Rental Option", "Guide"],
    badge: "Offbeat",
  },
  {
    id: 14,
    title: "Rishikesh River Rush",
    destination: "Rishikesh, Uttarakhand",
    country: "India",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80",
    price: 10500,
    days: 3,
    nights: 2,
    category: "adventure",
    groupTypes: ["friends", "solo", "couple"],
    rating: 4.6,
    reviews: 734,
    highlights: ["Grade 4 white-water rafting", "Bungee jump", "Beach camping"],
    includes: ["Tent Camp", "All Meals", "Rafting + Bungee", "Transport"],
    badge: "Bestseller",
  },
  {
    id: 15,
    title: "Kedarkantha Trek",
    destination: "Uttarkashi, Uttarakhand",
    country: "India",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&auto=format&fit=crop&q=80",
    price: 13500,
    days: 6,
    nights: 5,
    category: "adventure",
    groupTypes: ["friends", "solo", "family"],
    rating: 4.8,
    reviews: 298,
    highlights: ["Summit at 12,500 ft", "Snow camping", "Oak & rhododendron forests"],
    includes: ["Camping", "All Meals", "Certified Trek Guide", "Safety Gear"],
  },
  {
    id: 16,
    title: "Coorg Jungle & Coffee Trail",
    destination: "Coorg, Karnataka",
    country: "India",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80",
    price: 16000,
    days: 4,
    nights: 3,
    category: "adventure",
    groupTypes: ["family", "couple", "friends"],
    rating: 4.5,
    reviews: 214,
    highlights: ["Coffee plantation walk", "Elephant interaction", "Abbey Falls hike"],
    includes: ["Jungle Resort", "All Meals", "Nature Walk", "Transport"],
  },
  {
    id: 17,
    title: "Nepal Annapurna Base Camp",
    destination: "Pokhara, Nepal",
    country: "Nepal",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
    price: 48000,
    days: 12,
    nights: 11,
    category: "adventure",
    groupTypes: ["solo", "friends"],
    rating: 4.9,
    reviews: 189,
    highlights: ["ABC summit 4,130m", "Poon Hill sunrise", "Gurung village homestay"],
    includes: ["Tea Houses", "All Meals", "Permit Fees", "Licensed Guide"],
    badge: "Epic",
  },

  // ── HONEYMOON ────────────────────────────────────────────────────────────
  {
    id: 18,
    title: "Kashmir Heaven on Earth",
    destination: "Srinagar • Gulmarg • Pahalgam",
    country: "India",
    image: "https://images.unsplash.com/photo-1566837945700-30057527ade0?w=800&auto=format&fit=crop&q=80",
    price: 32000,
    days: 6,
    nights: 5,
    category: "honeymoon",
    groupTypes: ["couple"],
    rating: 4.9,
    reviews: 412,
    highlights: ["Dal Lake shikara ride", "Gulmarg gondola", "Tulip garden walk"],
    includes: ["Houseboat + Hotel", "Breakfast & Dinner", "Sightseeing", "Flight"],
    badge: "Bestseller",
  },
  {
    id: 19,
    title: "Santorini & Athens Dream",
    destination: "Athens • Santorini",
    country: "Greece",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&auto=format&fit=crop&q=80",
    price: 210000,
    days: 8,
    nights: 7,
    category: "honeymoon",
    groupTypes: ["couple"],
    rating: 5.0,
    reviews: 97,
    highlights: ["Oia sunset", "Acropolis tour", "Catamaran cruise"],
    includes: ["Boutique Cave Hotel", "Breakfast", "Return Flight", "Ferry"],
    badge: "Luxury",
  },
  {
    id: 20,
    title: "Coorg Romantic Retreat",
    destination: "Coorg, Karnataka",
    country: "India",
    image: "https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?w=800&auto=format&fit=crop&q=80",
    price: 18000,
    days: 3,
    nights: 2,
    category: "honeymoon",
    groupTypes: ["couple"],
    rating: 4.7,
    reviews: 321,
    highlights: ["Private pool villa", "Candlelight dinner", "Couples spa"],
    includes: ["Luxury Resort", "All Meals", "Spa Session", "Bonfire"],
    badge: "Romantic",
  },
  {
    id: 21,
    title: "Mauritius Sun & Sea",
    destination: "Mauritius",
    country: "Mauritius",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
    price: 125000,
    days: 6,
    nights: 5,
    category: "honeymoon",
    groupTypes: ["couple"],
    rating: 4.9,
    reviews: 178,
    highlights: ["Beachfront villa", "Underwater waterfall view", "Sunset catamaran"],
    includes: ["5-Star Resort", "All Meals", "Return Flight", "Island Tour"],
  },
  {
    id: 22,
    title: "Himachal Honeymoon Special",
    destination: "Shimla • Manali",
    country: "India",
    image: "https://images.unsplash.com/photo-1623848564040-8e5b3b08e8c1?w=800&auto=format&fit=crop&q=80",
    price: 21500,
    days: 7,
    nights: 6,
    category: "honeymoon",
    groupTypes: ["couple"],
    rating: 4.6,
    reviews: 445,
    highlights: ["Snow point visit", "Mall Road stroll", "Valley view cottage"],
    includes: ["Hotel", "Breakfast & Dinner", "Sightseeing", "AC Transport"],
    badge: "Trending",
  },
];